### CONSTANTES UTILIZADAS NO AMBIENTE

TOTAL_DIAS = 5
TOTAL_SALAS = 5
TOTAL_HORARIOS_DIA = 2
TOTAL_HORARIOS_GRADE = TOTAL_DIAS*TOTAL_SALAS*TOTAL_HORARIOS_DIA
MAX_ITERACOES_GRASP_PADRAO = 1000
MAX_ITERACOES_BUSCA_LOCAL_PADRAO = 1000
ALFA_RCL_PADRAO = 0.5
SOLUCAO_INICIAL_ALEATORIA_PADRAO = False
SOLUCAO_INICIAL_PADRAO = [[],
