### CONSTANTES UTILIZADAS NO AMBIENTE

# CONFIGURACAO DA GRADE ESCOLAR
TOTAL_DIAS = 5
TOTAL_SALAS = 5
TOTAL_HORARIOS_DIA = 2
TOTAL_HORARIOS_GRADE = TOTAL_DIAS*TOTAL_SALAS*TOTAL_HORARIOS_DIA

# INDICES DOS ELEMENTOS NO VETOR [PROFESSOR, DISCIPLINA, QUANTIDADE EXIGIDA DE HORARIOS] 
INDICE_PROFESSOR = 0
INDICE_DISCIPLINA = 1
INDICE_HORARIOS = 2

# VALORES PADRAO DOS METODOS
PADRAO_MAX_ITERACOES_GRASP = 1000
PADRAO_MAX_ITERACOES_BUSCA_LOCAL = 1000
PADRAO_ALFA_RCL = 0.5
PADRAO_FLAG_CALCULA_SOLUCAO_INICIAL = False
PADRAO_SOLUCAO_INICIAL = [[],
