### CONSTANTES UTILIZADAS NO AMBIENTE

# SEPARADOR DO ARQUIVO CSV DE ENTRADA
SEPARADOR_CSV=';'

# CONFIGURACAO DA GRADE ESCOLAR
TOTAL_DIAS = 5
TOTAL_SALAS = 5
TOTAL_HORARIOS_DIA = 2
TOTAL_AULAS_DIA = TOTAL_SALAS * TOTAL_HORARIOS_DIA 
TOTAL_HORARIOS_GRADE = TOTAL_DIAS*TOTAL_SALAS*TOTAL_HORARIOS_DIA
DIAS_DA_SEMANA = ['Segunda','Terça','Quarta','Quinta','Sexta']

# INDICES (POSICOES) DOS ELEMENTOS DA SOLUCAO [GRADE, FITNESS DA GRADE] 
INDICE_GRADE = 0
INDICE_FITNESS = 1

# INDICES (POSICOES) DOS ELEMENTOS NO VETOR INICIAL GERADO DO ARQUIVO CSV  
# [PROFESSOR, DISCIPLINA, QUANTIDADE EXIGIDA DE HORARIOS] 
# E NO VETOR AULAS [PROFESSOR, DISCIPLINA]
INDICE_PROFESSOR = 0
INDICE_DISCIPLINA = 1
INDICE_HORARIOS = 2

# REPRESENTACAO HORARIO VAGO NA GRADE
HORARIO_VAGO = 'VAGO'

# PESO DAS VIOLACOES NA FUNCAO OBJETIVO (FITNESS)
PESO_PROF_MESMO_HORARIO = 1
PESO_DISC_MESMO_DIA_SALA_DIFER = 0.1
PESO_DISC_MESMO_DIA_SALA_IGUAL = 0.05
PESO_PRIMEIRO_HORARIO_VAGO = 0.1
PESO_SEGUNDO_HORARIO_VAGO = 0.05

# VALORES PADRAO DOS METODOS
PADRAO_MAX_ITERACOES_GRASP = 1000
PADRAO_MAX_ITERACOES_BUSCA_LOCAL = 100
PADRAO_LIMITE_GRASP = 0
PADRAO_LIMITE_BUSCA_LOCAL = 0
PADRAO_ALFA_RCL = 0.5
PADRAO_FLAG_CALCULA_SOLUCAO_INICIAL = False
PADRAO_SOLUCAO_INICIAL_VAZIA = [[],float("inf")]

